http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: [ '/auth', '/auth/*' ]
    methods: [ 'POST' ]
  user:
    host: localhost
    paths: [ '/users', '/users/*' ]
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authService:
    url: 'http://localhost:3001'
  userService:
    url: 'http://localhost:3002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - user
      - music
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - log:
          action:
            message: 'proxy to all other services ${req.method} ${req.path}'
      - jwt:
          action:
            secretOrPublicKeyFile: './jwtRS256.key'
            checkCredentialExistence: true
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - proxy:
          action:
            serviceEndpoint: userService
            changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - log:
          action:
            message: 'proxy to auth ${req.method}'
      - proxy:
          action:
            serviceEndpoint: authService
            changeOrigin: true
#  userPipeline:
#    apiEndpoints:
#      - user
#    policies:
#      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
#      # - key-auth:
#      - log:
#          - action:
#              - message: 'proxy to user ${req.method}'
#      - proxy:
#          - action:
#              serviceEndpoint: userService
#              changeOrigin: true